# -*- coding: utf-8 -*-

STATUS_DRAFT = 0
STATUS_SUBMITTED = 1
STATUS_FAILED = 2
STATUS_PUBLISHED = 3
STATUS_DELETED = 4
STATUS_OFFLINE = 5
STATUS_HIDEEN = 6 # NOTE: admin hide
STATUS_ADMIN_OFFLINE = 7 # NOTE: admin take down
UNUSABLE_STATUSES = {STATUS_DELETED, STATUS_HIDEEN}
USABLE_STATUSES = {STATUS_DRAFT, STATUS_SUBMITTED, STATUS_FAILED, STATUS_PUBLISHED, STATUS_OFFLINE, STATUS_ADMIN_OFFLINE}
USABLE_STATUSES_WITHOUT_DRAFT = {STATUS_SUBMITTED, STATUS_FAILED, STATUS_PUBLISHED, STATUS_OFFLINE, STATUS_ADMIN_OFFLINE}
STAFF_ONLY_ACTIONS = {STATUS_FAILED, STATUS_PUBLISHED, STATUS_HIDEEN, STATUS_ADMIN_OFFLINE}

STAFF_ACTION_MAPPING = {
    STATUS_SUBMITTED: {
        STATUS_FAILED,
        STATUS_PUBLISHED,
    },
    STATUS_PUBLISHED: {
        STATUS_ADMIN_OFFLINE,
    },
}

COPYRIGHT_WARNING_REASON_CODE = 301

COPYRIGHT_WARNING_UNREACHED_BANNED_COUNTS = [1, 2]

COPYRIGHT_WARNING_REACHED_BANNED_COUNT = 3

UPDATE_VALID_ACTIONS = {STATUS_SUBMITTED, STATUS_DRAFT}

ARTICLE_STATUS_REVISION = 'revision'
ARTICLE_STATUS_SUBMITTED = 'submitted'

ARTICLE_SUBMIT_LIMIT = 3
